# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_m1QQf9aDFp2Wm69EYFFuBjGODqgO7YX
"""

import cv2
import sys

# Importamos módulos
from Guarda_Pixeles import cargar_imagen
from Escala_grises import convertir_a_grises
from Recorre_Array import analizar_arreglo_figuras

def procesar_imagen(ruta_imagen):
    try:
        imagen = cargar_imagen(ruta_imagen)
    except FileNotFoundError as e:
        print(e)
        return
    gris = convertir_a_grises(imagen)
    _, binarizada = cv2.threshold(gris, 240, 255, cv2.THRESH_BINARY_INV)
    contornos, _ = cv2.findContours(binarizada, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    analizar_arreglo_figuras(contornos, imagen)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Uso incorrecto. Ejecuta:")
        print("python main.py <ruta_de_la_imagen.bmp>")
    else:
        ruta = sys.argv[1]
        procesar_imagen(ruta)