# -*- coding: utf-8 -*-
"""Recorre_Array

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9oNfwpyXVeZr9aGnE1ywMIMubVdqYcl
"""

import cv2

from Clasificacion_figura import clasificacion
from Valor_hexadecimal import rgb_a_hexadecimal


def analizar_arreglo_figuras(contornos, imagen):
    """
    Recorre el array de contornos, clasifica cada figura y obtiene su color.
    """
    if not contornos:
        print("No se detectaron figuras en la imagen.")
        return

    print(f"Se encontraron {len(contornos)} figura(s). \n Analizando...")
    print("-" * 30)

    for i, contorno in enumerate(contornos):

        # aproximamos vertices
        perimetro = cv2.arcLength(contorno, True)
        # 0.04 para ver qué tan estricta es la aprox.
        aproximacion = cv2.approxPolyDP(contorno, 0.04 * perimetro, True)
        puntas = len(aproximacion)

        # Si el polígono tiene más de 6 puntas, asumiremos que es un círculo
        if puntas > 6:
            puntas = 0

        categoria = clasificacion(puntas)

        # para el color calculamos los 'momentos' de la figura para encontrar sus coordenadas centrales
        M = cv2.moments(contorno)
        if M["m00"] != 0:
            cX = int(M["m10"] / M["m00"]) # Coordenada X del centro
            cY = int(M["m01"] / M["m00"]) # Coordenada Y del centro
        else:
            cX, cY = contorno[0][0]

        # para el color exacto del pixel central
        color_bgr = imagen[cY, cX]
        blue, green, red = color_bgr[0], color_bgr[1], color_bgr[2]

        # módulo para convertir a hexadecimal
        hex_color = rgb_a_hexadecimal(red, green, blue)

        # para el reporte
        print(f"Figura {i+1}:")
        print(f"  - Categoría: {categoria}")
        print(f"  - Color (Hex): {hex_color}")
        print("-" * 30)